import "./canonical-switch-share.test";
import "./client-api-error.test";
import "./compose-secrets.test";
import "./image-optimization.test";
import "./master-switch-popup-share.test";
import "./master-switch-sort.test";
import "./switch-filters.test";
import "./partner-api.test";
import "./force-curves.test";
