'use client'
import { useState } from 'react'

type Candidate = { id:string; displayName:string; repositoryPath:string; revision:string|null; contentHash:string|null }
type Master = { id:string; name:string; manufacturer:string|null; technology:string|null; type:string|null }
type Review = { id:string; kind:string; reason:string; catalogEntryId:string|null; masterSwitch:Master|null; catalogEntry:Candidate|null; candidates:Candidate[] }
const technologies=['MECHANICAL','OPTICAL','MAGNETIC','INDUCTIVE','ELECTRO_CAPACITIVE']

export default function ForceCurveReviewQueue({initialReviews}:{initialReviews:Review[]}) {
 const [reviews,setReviews]=useState(initialReviews),[selected,setSelected]=useState<Record<string,string>>({}),[search,setSearch]=useState<Record<string,string>>({}),[results,setResults]=useState<Record<string,Candidate[]>>({}),[technology,setTechnology]=useState<Record<string,string>>({})
 const [masterSearch,setMasterSearch]=useState<Record<string,string>>({}),[masterResults,setMasterResults]=useState<Record<string,Master[]>>({}),[selectedMaster,setSelectedMaster]=useState<Record<string,string>>({}),[errors,setErrors]=useState<Record<string,string>>({})
 async function json(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
 async function find(r:Review){try{const response=await fetch(`/api/admin/force-curves/catalog?query=${encodeURIComponent(search[r.id]||'')}`);const data=await json(response);setResults(v=>({...v,[r.id]:data}));setErrors(v=>({...v,[r.id]:''}))}catch(error){setErrors(v=>({...v,[r.id]:error instanceof Error?error.message:'Search failed'}))}}
 async function findMasters(r:Review){try{const response=await fetch(`/api/admin/force-curves/master-switches?query=${encodeURIComponent(masterSearch[r.id]||'')}`);const data=await json(response);setMasterResults(v=>({...v,[r.id]:data}));setErrors(v=>({...v,[r.id]:''}))}catch(error){setErrors(v=>({...v,[r.id]:error instanceof Error?error.message:'Search failed'}))}}
 async function link(r:Review){const masterSwitchId=selectedMaster[r.id],catalogEntryId=selected[r.id]||r.catalogEntryId||r.candidates[0]?.id;if(!masterSwitchId||!catalogEntryId)return;try{const response=await fetch('/api/admin/force-curves/reviews',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:r.id,masterSwitchId,catalogEntryId})});await json(response);const master=(masterResults[r.id]||[]).find(m=>m.id===masterSwitchId)!;setReviews(items=>items.map(item=>item.id===r.id?{...item,masterSwitch:master,catalogEntryId}:item));setTechnology(v=>({...v,[r.id]:master.technology||''}));setErrors(v=>({...v,[r.id]:''}))}catch(error){setErrors(v=>({...v,[r.id]:error instanceof Error?error.message:'Link failed'}))}}
 async function verify(r:Review){const catalogEntryId=selected[r.id]||r.catalogEntryId;if(!catalogEntryId||!r.masterSwitch?.manufacturer||!technology[r.id])return;try{await json(await fetch('/api/admin/force-curves/reviews',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:r.id,catalogEntryId,manufacturer:r.masterSwitch.manufacturer,technology:technology[r.id]})}));setReviews(items=>items.map(item=>item.id===r.id?{...item,catalogEntryId,candidates:(results[r.id]||r.candidates).filter(c=>c.id===catalogEntryId)}:item));setErrors(v=>({...v,[r.id]:''}))}catch(error){setErrors(v=>({...v,[r.id]:error instanceof Error?error.message:'Verification failed'}))}}
 async function resolve(r:Review,resolution:'MANUALLY_APPROVED'|'REJECTED'|'NO_MATCH'){try{await json(await fetch('/api/admin/force-curves/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:r.id,resolution,catalogEntryId:selected[r.id]||r.catalogEntryId||undefined})}));setReviews(items=>items.filter(item=>item.id!==r.id))}catch(error){setErrors(v=>({...v,[r.id]:error instanceof Error?error.message:'Resolution failed'}))}}
 if(!reviews.length)return <p>No open cases.</p>
 return <div className="space-y-4">{reviews.map(r=>{const choices=results[r.id]||r.candidates;return <article key={r.id} className="rounded border p-4 space-y-2"><h2 className="font-semibold">{r.masterSwitch?`${r.masterSwitch.manufacturer} ${r.masterSwitch.name}`:'Unlinked source review'}</h2><p>{r.kind}: {r.reason}</p><input className="border p-1" aria-label="Search exact catalog path" value={search[r.id]||''} onChange={e=>setSearch(v=>({...v,[r.id]:e.target.value}))}/><button className="ml-2" onClick={()=>find(r)}>Search curves</button>{choices.length>0&&<select className="block border p-1" aria-label="Exact curve path" value={selected[r.id]||r.catalogEntryId||''} onChange={e=>setSelected(v=>({...v,[r.id]:e.target.value}))}><option value="">Select exact path</option>{choices.map(c=><option key={c.id} value={c.id}>{c.repositoryPath} [{c.id}]</option>)}</select>}{!r.masterSwitch&&<div className="rounded bg-gray-50 p-2"><input className="border p-1" aria-label="Search approved master switch" value={masterSearch[r.id]||''} onChange={e=>setMasterSearch(v=>({...v,[r.id]:e.target.value}))}/><button className="ml-2" onClick={()=>findMasters(r)}>Search approved masters</button>{(masterResults[r.id]||[]).length>0&&<select className="block border p-1 mt-2" aria-label="Exact master switch" value={selectedMaster[r.id]||''} onChange={e=>setSelectedMaster(v=>({...v,[r.id]:e.target.value}))}><option value="">Select exact master ID</option>{masterResults[r.id].map(m=><option key={m.id} value={m.id}>{m.manufacturer} {m.name} — {m.technology} [{m.id}]</option>)}</select>}<button className="mt-2" onClick={()=>link(r)}>Attach audited exact link</button></div>}{r.masterSwitch&&<><select className="border p-1" aria-label="Verified technology" value={technology[r.id]||r.masterSwitch.technology||''} onChange={e=>setTechnology(v=>({...v,[r.id]:e.target.value}))}><option value="">Verify technology</option>{technologies.map(t=><option key={t}>{t}</option>)}</select><button className="ml-2" onClick={()=>verify(r)}>Verify metadata & attach</button><div>{(selected[r.id]||r.catalogEntryId)&&<button onClick={()=>resolve(r,'MANUALLY_APPROVED')}>Approve exact path</button>}<button className="ml-2" onClick={()=>resolve(r,'REJECTED')}>Reject</button><button className="ml-2" onClick={()=>resolve(r,'NO_MATCH')}>No match</button></div></>}{errors[r.id]&&<p role="alert" className="text-red-700">{errors[r.id]}</p>}</article>})}</div>
}
