'use client'
import { useMemo, useState } from 'react'

type Candidate={id:string;displayName:string;repositoryPath:string;revision:string|null;contentHash:string|null;manufacturer:string|null;technology:string|null}
type Master={id:string;name:string;manufacturer:string|null;technology:string|null}
type Evidence={id:string;kind:string;reason:string;status:'OPEN'|'RESOLVED';catalogEntryId:string|null;masterSwitch:Master|null;candidates:Candidate[]}
type Item={sourceKey:string;bucket:string;confidence:number;actionable:boolean;deferred:boolean;status:'OPEN'|'RESOLVED';evidence:Evidence[]}
type Queue={items:Item[];counts:Record<string,number>;rawReviewCount:number;uniqueSourceCount:number;openSourceCount:number;resolvedSourceCount:number;remainingActionable:number;deferredCount:number}

export default function ForceCurveReviewQueue({initialQueue}:{initialQueue:Queue}){
 const [queue,setQueue]=useState(initialQueue),[query,setQuery]=useState(''),[bucket,setBucket]=useState('ALL'),[status,setStatus]=useState('OPEN'),[busy,setBusy]=useState(''),[error,setError]=useState('')
 const [masterQuery,setMasterQuery]=useState<Record<string,string>>({}),[masterResults,setMasterResults]=useState<Record<string,Master[]>>({}),[chosenMaster,setChosenMaster]=useState<Record<string,string>>({})
 const items=useMemo(()=>queue.items.filter(item=>(bucket==='ALL'||item.bucket===bucket)&&(status==='ALL'||(status==='DEFERRED'?item.status==='OPEN'&&item.deferred:item.status===status&&!item.deferred))&&`${item.sourceKey} ${item.evidence.flatMap(e=>[e.reason,e.kind,e.masterSwitch?.name,e.masterSwitch?.manufacturer,...e.candidates.map(c=>c.repositoryPath)]).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[queue,query,bucket,status])
 async function mutate(item:Item,body:object){setBusy(item.sourceKey);setError('');try{const response=await fetch('/api/admin/force-curves/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Request failed');const fresh=await fetch('/api/admin/force-curves/reviews');if(!fresh.ok)throw new Error('Saved, but refresh failed');setQueue(await fresh.json())}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy('')}}
 async function resolve(item:Item,resolution:'MANUALLY_APPROVED'|'NO_MATCH'){const first=item.evidence.find(e=>e.status==='OPEN')!,candidate=first.candidates.find(c=>c.id===first.catalogEntryId)||first.candidates[0];await mutate(item,{reviewId:first.id,resolution,catalogEntryId:resolution==='MANUALLY_APPROVED'?candidate?.id:undefined,reason:'Admin source-centric queue decision'})}
 async function findMasters(item:Item){const q=masterQuery[item.sourceKey]||'';if(q.trim().length<2){setError('MasterSwitch search requires at least 2 characters');return}setBusy(item.sourceKey);setError('');try{const response=await fetch(`/api/admin/force-curves/master-switches?query=${encodeURIComponent(q)}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'Search failed');setMasterResults(v=>({...v,[item.sourceKey]:data}))}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setBusy('')}}
 async function chooseMaster(item:Item){const first=item.evidence.find(e=>e.status==='OPEN')!,catalog=first.candidates.find(c=>c.id===first.catalogEntryId)||first.candidates[0],masterSwitchId=chosenMaster[item.sourceKey],reviewIds=item.evidence.filter(e=>e.status==='OPEN').map(e=>e.id);if(!catalog||!masterSwitchId){setError('Select a catalog candidate and MasterSwitch');return}setBusy(item.sourceKey);setError('');try{const response=await fetch('/api/admin/force-curves/reviews',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewIds,masterSwitchId,catalogEntryId:catalog.id})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Link failed');const fresh=await fetch('/api/admin/force-curves/reviews');setQueue(await fresh.json())}catch(e){setError(e instanceof Error?e.message:'Link failed')}finally{setBusy('')}}
 return <section className="space-y-4">
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-5" aria-label="Queue progress"><Stat label="Unique sources" value={queue.uniqueSourceCount}/><Stat label="Open sources" value={queue.openSourceCount}/><Stat label="Resolved sources" value={queue.resolvedSourceCount}/><Stat label="Remaining actionable" value={queue.remainingActionable}/><Stat label="Deferred" value={queue.deferredCount}/></div>
  <div className="sticky top-0 z-10 grid gap-2 rounded-lg border bg-white p-3 shadow-sm sm:grid-cols-3 dark:bg-gray-950"><input className="min-h-11 rounded border px-3" placeholder="Search source, switch, or path" aria-label="Search queue" value={query} onChange={e=>setQuery(e.target.value)}/><select className="min-h-11 rounded border px-3" aria-label="Bucket" value={bucket} onChange={e=>setBucket(e.target.value)}><option value="ALL">All buckets</option>{['ACTIONABLE','DUPLICATE','NO_MATCH','AMBIGUITY','CONFLICT','OTHER'].map(x=><option key={x} value={x}>{x} ({queue.counts[x]||0})</option>)}</select><select className="min-h-11 rounded border px-3" aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="OPEN">Open</option><option value="DEFERRED">Deferred</option><option value="RESOLVED">Resolved</option><option value="ALL">All statuses</option></select></div>
  {error&&<p role="alert" className="rounded bg-red-100 p-3 text-red-900">{error}</p>}
  <p className="text-sm text-gray-600">Showing {items.length} source items. Bulk approval appears only for homogeneous, exact, high-confidence repeated evidence.</p>
  <div className="space-y-4">{items.map(item=>{const first=item.evidence[0],candidate=first.candidates.find(c=>c.id===first.catalogEntryId)||first.candidates[0],master=first.masterSwitch;return <article key={item.sourceKey} className="overflow-hidden rounded-xl border bg-white shadow-sm dark:bg-gray-950">
   <header className="flex flex-wrap items-center justify-between gap-2 border-b p-3"><div><h2 className="font-semibold">{item.sourceKey}</h2><p className="text-xs text-gray-500">{item.evidence.length} evidence row{item.evidence.length===1?'':'s'} · confidence {Math.round(item.confidence*100)}%</p></div><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-800">{item.deferred?'DEFERRED':item.bucket}</span></header>
   <div className="grid gap-0 md:grid-cols-2"><div className="border-b p-4 md:border-b-0 md:border-r"><h3 className="mb-2 text-xs font-bold uppercase tracking-wide text-gray-500">Source identity & evidence</h3><p className="font-medium">{candidate?.displayName||'No catalog candidate'}</p><p className="break-all text-sm">{candidate?.repositoryPath||first.reason}</p>{candidate&&<dl className="mt-2 text-xs text-gray-600"><dt>Hash</dt><dd className="break-all">{candidate.contentHash||'missing'}</dd><dt>Revision</dt><dd>{candidate.revision||'unknown'}</dd></dl>}<details className="mt-3"><summary className="cursor-pointer text-sm">All evidence ({item.evidence.length})</summary><ul className="mt-2 space-y-1 text-xs">{item.evidence.map(e=><li key={e.id}>{e.kind}: {e.reason}</li>)}</ul></details></div>
    <div className="p-4"><h3 className="mb-2 text-xs font-bold uppercase tracking-wide text-gray-500">Candidate MasterSwitch</h3>{master?<><p className="font-medium">{master.manufacturer} {master.name}</p><p className="text-sm">{master.technology||'Technology unknown'} · ID {master.id}</p></>:<p className="text-sm text-amber-700">No MasterSwitch attached.</p>}{item.status==='OPEN'&&<div className="mt-3 space-y-2 rounded border p-2"><label className="block text-xs font-medium">Choose another MasterSwitch</label><div className="flex gap-2"><input className="min-h-11 min-w-0 flex-1 rounded border px-2" value={masterQuery[item.sourceKey]||candidate?.displayName||''} onChange={e=>setMasterQuery(v=>({...v,[item.sourceKey]:e.target.value}))}/><button className="rounded border px-3" onClick={()=>findMasters(item)}>Search</button></div>{(masterResults[item.sourceKey]||[]).length>0&&<><select className="min-h-11 w-full rounded border px-2" value={chosenMaster[item.sourceKey]||''} onChange={e=>setChosenMaster(v=>({...v,[item.sourceKey]:e.target.value}))}><option value="">Select exact master</option>{masterResults[item.sourceKey].map(m=><option key={m.id} value={m.id}>{m.manufacturer} {m.name} — {m.technology}</option>)}</select><button className="min-h-11 w-full rounded bg-blue-700 px-3 text-white" onClick={()=>chooseMaster(item)}>Attach selected MasterSwitch</button></>}</div>}</div></div>
   {item.status==='OPEN'&&<footer className="flex flex-col gap-2 border-t p-3 sm:flex-row">{item.actionable&&candidate&&<button disabled={!!busy} className="min-h-11 rounded bg-green-700 px-4 text-white disabled:opacity-50" onClick={()=>{const ids=item.evidence.filter(e=>e.status==='OPEN').map(e=>e.id);return ids.length>1?mutate(item,{action:'BULK_APPROVE',reviewIds:ids,catalogEntryId:candidate.id,reason:'Homogeneous exact source evidence'}):resolve(item,'MANUALLY_APPROVED')}}>{item.evidence.filter(e=>e.status==='OPEN').length>1?`Approve group (${item.evidence.filter(e=>e.status==='OPEN').length})`:'Approve suggestion'}</button>}{master&&<button disabled={!!busy} className="min-h-11 rounded border border-red-300 px-4 text-red-800" onClick={()=>mutate(item,{action:'GROUP_NO_MATCH',reviewIds:item.evidence.filter(e=>e.status==='OPEN').map(e=>e.id),reason:'Admin source-centric durable no-match decision'})}>Durable NO_MATCH ({item.evidence.filter(e=>e.status==='OPEN').length})</button>}<button disabled={!!busy} className="min-h-11 rounded border px-4" onClick={()=>mutate(item,{action:'DEFER',reviewIds:item.evidence.filter(e=>e.status==='OPEN').map(e=>e.id),reason:'Deferred from admin queue'})}>{item.deferred?'Deferred':'Skip / defer'}</button></footer>}
  </article>})}</div>{!items.length&&<p className="rounded border p-8 text-center">No source items match these filters.</p>}
 </section>
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-lg border p-3"><div className="text-2xl font-bold">{value}</div><div className="text-xs text-gray-500">{label}</div></div>}
