'use client'
import { useState } from 'react'
type Candidate = { id:string; displayName:string; repositoryPath:string }
type Review = { id:string; kind:string; reason:string; catalogEntryId:string|null; masterSwitch:{id:string;name:string;manufacturer:string|null}|null; catalogEntry:Candidate|null; candidates:Candidate[] }
const technologies=['MECHANICAL','OPTICAL','MAGNETIC','INDUCTIVE','ELECTRO_CAPACITIVE']
export default function ForceCurveReviewQueue({initialReviews}:{initialReviews:Review[]}) {
 const [reviews,setReviews]=useState(initialReviews),[selected,setSelected]=useState<Record<string,string>>({}),[search,setSearch]=useState<Record<string,string>>({}),[results,setResults]=useState<Record<string,Candidate[]>>({}),[technology,setTechnology]=useState<Record<string,string>>({})
 async function find(r:Review){const response=await fetch(`/api/admin/force-curves/catalog?query=${encodeURIComponent(search[r.id]||'')}`);if(response.ok){const data=await response.json();setResults(v=>({...v,[r.id]:data}))}}
 async function verify(r:Review){const catalogEntryId=selected[r.id];if(!catalogEntryId||!r.masterSwitch?.manufacturer||!technology[r.id])return;const response=await fetch('/api/admin/force-curves/reviews',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:r.id,catalogEntryId,manufacturer:r.masterSwitch.manufacturer,technology:technology[r.id]})});if(response.ok)setReviews(items=>items.map(item=>item.id===r.id?{...item,catalogEntryId,candidates:(results[r.id]||[]).filter(c=>c.id===catalogEntryId)}:item))}
 async function resolve(r:Review,resolution:'MANUALLY_APPROVED'|'REJECTED'|'NO_MATCH'){const response=await fetch('/api/admin/force-curves/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:r.id,resolution,catalogEntryId:selected[r.id]||r.catalogEntryId})});if(response.ok)setReviews(items=>items.filter(item=>item.id!==r.id))}
 if(!reviews.length)return <p>No open cases.</p>
 return <div className="space-y-4">{reviews.map(r=>{const choices=results[r.id]||r.candidates;return <article key={r.id} className="rounded border p-4"><h2 className="font-semibold">{r.masterSwitch?.manufacturer} {r.masterSwitch?.name}</h2><p>{r.kind}: {r.reason}</p><input aria-label="Search exact catalog path" value={search[r.id]||''} onChange={e=>setSearch(v=>({...v,[r.id]:e.target.value}))}/><button onClick={()=>find(r)}>Search</button>{choices.length>0&&<select aria-label="Exact curve path" value={selected[r.id]||r.catalogEntryId||''} onChange={e=>setSelected(v=>({...v,[r.id]:e.target.value}))}><option value="">Select exact path</option>{choices.map(c=><option key={c.id} value={c.id}>{c.repositoryPath}</option>)}</select>}<select aria-label="Verified technology" value={technology[r.id]||''} onChange={e=>setTechnology(v=>({...v,[r.id]:e.target.value}))}><option value="">Verify technology</option>{technologies.map(t=><option key={t}>{t}</option>)}</select><button onClick={()=>verify(r)}>Verify metadata & attach</button><div>{(selected[r.id]||r.catalogEntryId)&&<button onClick={()=>resolve(r,'MANUALLY_APPROVED')}>Approve exact path</button>}<button onClick={()=>resolve(r,'REJECTED')}>Reject</button><button onClick={()=>resolve(r,'NO_MATCH')}>No match</button></div></article>})}</div>
}
